// Two-level lookup: API-Football English names (primary) + Spanish display names (compat).
// flagUrl is called with English names in Supervivencia and with t()-translated Spanish
// names in PredictorFluido — both must resolve correctly.
//
// Avoid duplicate keys: names identical in English and Spanish only appear once (English side).

export const TEAM_FLAGS: Record<string, string> = {
  // ── API-Football English names (all WC 2026 teams + common extras) ──────────
  "Algeria":               "dz",
  "Argentina":             "ar",
  "Australia":             "au",
  "Austria":               "at",
  "Belgium":               "be",
  "Bosnia & Herzegovina":  "ba",
  "Bosnia and Herzegovina":"ba",
  "Bolivia":               "bo",
  "Brazil":                "br",
  "Canada":                "ca",
  "Cape Verde Islands":    "cv",
  "Cape Verde":            "cv",
  "Chile":                 "cl",
  "Colombia":              "co",
  "Congo DR":              "cd",
  "DR Congo":              "cd",
  "Costa Rica":            "cr",
  "Croatia":               "hr",
  "Curaçao":               "cw",
  "Czech Republic":        "cz",
  "Denmark":               "dk",
  "Ecuador":               "ec",
  "Egypt":                 "eg",
  "El Salvador":           "sv",
  "England":               "gb-eng",
  "France":                "fr",
  "Germany":               "de",
  "Ghana":                 "gh",
  "Greece":                "gr",
  "Guinea":                "gn",
  "Haiti":                 "ht",
  "Honduras":              "hn",
  "Hungary":               "hu",
  "Iran":                  "ir",
  "Iraq":                  "iq",
  "Ivory Coast":           "ci",
  "Jamaica":               "jm",
  "Japan":                 "jp",
  "Jordan":                "jo",
  "Mali":                  "ml",
  "Mexico":                "mx",
  "Morocco":               "ma",
  "Netherlands":           "nl",
  "New Zealand":           "nz",
  "Nigeria":               "ng",
  "Norway":                "no",
  "Panama":                "pa",
  "Paraguay":              "py",
  "Peru":                  "pe",
  "Poland":                "pl",
  "Portugal":              "pt",
  "Qatar":                 "qa",
  "Romania":               "ro",
  "Saudi Arabia":          "sa",
  "Scotland":              "gb-sct",
  "Senegal":               "sn",
  "Serbia":                "rs",
  "Slovakia":              "sk",
  "Slovenia":              "si",
  "South Africa":          "za",
  "South Korea":           "kr",
  "Spain":                 "es",
  "Sweden":                "se",
  "Switzerland":           "ch",
  "Tunisia":               "tn",
  "Türkiye":               "tr",
  "Turkey":                "tr",
  "Ukraine":               "ua",
  "Albania":               "al",
  "USA":                   "us",
  "United States":         "us",
  "Uruguay":               "uy",
  "Uzbekistan":            "uz",
  "Venezuela":             "ve",
  "Wales":                 "gb-wls",

  // ── Spanish display names only (PredictorFluido: t("England") → "Inglaterra") ─
  // Only keys that differ from their English counterpart are listed here.
  "México":                "mx",
  "Brasil":                "br",
  "España":                "es",
  "Alemania":              "de",
  "Inglaterra":            "gb-eng",
  "Francia":               "fr",
  "Países Bajos":          "nl",
  "Bélgica":               "be",
  "Croacia":               "hr",
  "Suiza":                 "ch",
  "Polonia":               "pl",
  "Marruecos":             "ma",
  "Japón":                 "jp",
  "Corea del Sur":         "kr",
  "Estados Unidos":        "us",
  "EE.UU":                 "us",
  "Canadá":                "ca",
  "Perú":                  "pe",
  "Gales":                 "gb-wls",
  "Arabia Saudita":        "sa",
  "Irán":                  "ir",
  "Túnez":                 "tn",
  "Costa de Marfil":       "ci",
  "RD Congo":              "cd",
  "Argelia":               "dz",
  "Jordania":              "jo",
  "Uzbekistán":            "uz",
  "Panamá":                "pa",
  "Cabo Verde":            "cv",
  "Turquía":               "tr",
  "Irak":                  "iq",
  "Noruega":               "no",
  "Escocia":               "gb-sct",
  "Haití":                 "ht",
  "Bosnia y Herzegovina":  "ba",
  "Curazao":               "cw",
  "Egipto":                "eg",
  "Nueva Zelanda":         "nz",
  "Sudáfrica":             "za",
  "República Checa":       "cz",
  "Dinamarca":             "dk",
  "Suecia":                "se",
  "Ucrania":               "ua",
  "Camerún":               "cm",
  "Cameroon":              "cm",
};

export function flagUrl(team: string, width: 20 | 40 | 80 = 40): string {
  if (!team) return "";
  const code = TEAM_FLAGS[team];
  return code ? `https://flagcdn.com/w${width}/${code}.png` : "";
}
