"""add_elapsed_to_matches

Revision ID: 5902ad80d508
Revises: 922a425a7294
Create Date: 2026-06-01 12:45:12.154789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5902ad80d508'
down_revision: Union[str, Sequence[str], None] = '922a425a7294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('elapsed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'elapsed')
    # ### end Alembic commands ###
