"""add_total_points_is_alive_to_users

Revision ID: 922a425a7294
Revises: a3c7e891f024
Create Date: 2026-05-28 17:32:50.651688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922a425a7294'
down_revision: Union[str, Sequence[str], None] = 'a3c7e891f024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_points', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_alive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_alive')
    op.drop_column('users', 'total_points')
    # ### end Alembic commands ###
