"""add_paid_flags_to_users

Revision ID: cead32f7945c
Revises: 5902ad80d508
Create Date: 2026-06-01 13:46:59.215169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cead32f7945c'
down_revision: Union[str, Sequence[str], None] = '5902ad80d508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_paid_classic', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('has_paid_survival', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('has_extra_life', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_extra_life')
    op.drop_column('users', 'has_paid_survival')
    op.drop_column('users', 'has_paid_classic')
    # ### end Alembic commands ###
